services:
  mediamtx-server:
    image: bluenviron/mediamtx:latest
    ports:
      - "8554:8554"         # RTSP (server)
      - "8888:8888"         # HLS (HTTP)
      - "8889:8889"         # WebRTC (HTTP)
      - "8189:8189/udp"     # WebRTC ICE/UDP
      - "8890:8890/udp"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    environment:
      MTX_HLS: "yes"
      MTX_WEBRTC: "yes"
    restart: unless-stopped