services:
  mediamtx-server:
    build: ./infra/mediamtx
    ports:
      - "8554:8554"         # RTSP (server)
      - "8889:8889"         # WebRTC (HTTP)
      - "8189:8189/udp"     # WebRTC ICE/UDP
      - "8890:8890/udp"
      - "9997:9997"         # API 
    volumes:
      - ./infra/mediamtx/mediamtx.yml:/mediamtx.yml:ro
    environment:
      MTX_WEBRTC: "yes"
      MTX_RTSPTRANSPORTS: "tcp"
      MTX_WEBRTCADDITIONALHOSTS: "127.0.0.1"
    restart: unless-stopped
  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./api/.env
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data --appendonly yes
    healthcheck:
      test: ["CMD-SHELL", "redis cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: always
  
volumes:
  pgdata:
  redisdata: