services:
  mediamtx-server:
    build: ./infra/mediamtx
    ports:
      - "8554:8554" # RTSP (server)
      - "8889:8889" # WebRTC (HTTP)
      - "8189:8189/udp" # WebRTC ICE/UDP
      - "8890:8890/udp"
      - "9997:9997" # API
    volumes:
      - ./infra/mediamtx/mediamtx.yml:/mediamtx.yml:ro
      - ./recordings:/recordings # Mount the recordings dir
    environment:
      MTX_WEBRTC: "yes"
      MTX_RTSPTRANSPORTS: "tcp"
      MTX_WEBRTCADDITIONALHOSTS: "10.0.0.8,localhost"
    restart: unless-stopped
  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./api/.env
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data --appendonly yes
    healthcheck:
      test: ["CMD-SHELL", "redis cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: always
  rabbitmq:
    image: rabbitmq:4-management
    env_file:
      - ./api/.env
    volumes:
      - rabbitmqdata:/data
    ports:
      - "5672:5672" # AMPQ Port
      - "15672:15672" # RabbitMQ Management UI port
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
  ovms:
    image: openvino/model_server:latest
    ports:
      - "9000:9000" # gRPC
      - "9001:9001" # REST
    command: >
      --port 9000
      --rest_port 9001
      --config_path /models/config.json
    volumes:
      - ./models/intel/person-detection-retail-0013/FP16:/models/person-detection-retail-0013/1:ro
      - ./models/config.json:/models/config.json:ro
    restart: unless-stopped
  minio:
    image: minio/minio:latest
    env_file:
      - ./api/.env
    volumes:
      - minio:/data
    ports:
      - "9002:9000"
      - "9003:9001"
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:
  minio:
